### ISSUE TITLE
Error on 'bundle install' with json (1.8.1)

### ISSUE THREAD

**Issue by kirkins** [swanson/lagom#41]
Fresh fork trying to bundle and get the following error:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20170320-11214-ulm9qujson-1.8.1/gems/json-1.8.1/ext/json/ext/generator
/usr/bin/ruby -r ./siteconf20170320-11214-1ca92it.rb extconf.rb
creating Makefile

current directory: /tmp/bundler20170320-11214-ulm9qujson-1.8.1/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /tmp/bundler20170320-11214-ulm9qujson-1.8.1/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from /usr/include/bits/libc-header-start.h:33:0,
                 from /usr/include/stdio.h:28,
                 from /usr/include/ruby-2.4.0/ruby/defines.h:101,
                 from /usr/include/ruby-2.4.0/ruby/ruby.h:36,
                 from /usr/include/ruby-2.4.0/ruby.h:33,
                 from ../fbuffer/fbuffer.h:5,
                 from generator.c:1:
/usr/include/features.h:373:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^~~~~~~~~~
generator.c: In function ‘generate_json’:
generator.c:840:25: error: ‘rb_cFixnum’ undeclared (first use in this function)
     } else if (klass == rb_cFixnum) {
                         ^~~~~~~~~~
generator.c:840:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:842:25: error: ‘rb_cBignum’ undeclared (first use in this function)
     } else if (klass == rb_cBignum) {
                         ^~~~~~~~~~
make: *** [Makefile:242: generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /tmp/bundler20170320-11214-ulm9qujson-1.8.1/gems/json-1.8.1 for inspection.
Results logged to /tmp/bundler20170320-11214-ulm9qujson-1.8.1/extensions/x86_64-linux/2.4.0/json-1.8.1/gem_make.out

An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.

```

Edit possibly a Ruby 2.4 issue? http://stackoverflow.com/a/41368000/773263

**Comment by kirkins** [comment]
Here are the [changes I made to get working with ruby 2.4](https://github.com/swanson/lagom/pull/42/files)

I also had to use: `jekyll serve bundle exec` in place of `jekyll serve`.
